spring:
  servlet:
    multipart:
      location: E:/tmp
      max-file-size: 10MB
      max-request-size: 20MB
      file-size-threshold: 1MB
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.226.130:3306/radish_master?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      # 连接池最大连接数
      maximum-pool-size: 10
      # 连接池最小空闲连接数
      minimum-idle: 5
      # 空闲连接的最大等待时间（单位：毫秒）
      idle-timeout: 30000
      # 获取连接的超时时间（单位：毫秒）
      connection-timeout: 20000
      # 连接的最大生命周期（单位：毫秒）
      max-lifetime: 180000
      # 连接池名称
      pool-name: cyx-datasource-pool
      # 数据性能监测jconsole
      register-mbeans: true
      # 连接验证的 SQL 查询
      connection-test-query: SELECT 1
      # 连接验证的超时时间（单位：毫秒）
      validation-timeout: 5000
  data:
    redis:
      host: 192.168.226.130
      port: 6379
      # 密码，未配置密码可不填
      password: 123456
      # 数据源
      database: 15
      # 连接超时（单位：毫秒）
      connect-timeout: 2000
      # 响应超时（单位毫秒）
      timeout: 5000
      # redis连接池
      lettuce:
        pool:
          # 连接池中的最大连接数
          max-active: 10
          # 最大空闲连接数
          max-idle: 8
          # 最小空闲连接数
          min-idle: 2
          # 连接池获取连接的最大等待时间（单位：毫秒）
          max-wait: 5000
#日志
logging:
  level:
    com.baomidou.mybatisplus: debug
    org.mybatis: debug
    com.soft.base.mapper: debug
    com.soft.cyx.mapper: debug
    root: info
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  config: classpath:logback-spring.xml
  file:
    name: logs/develop.log
#临时文件存储路径
tmp:
  path: E:/tmp
#限流
rate-limit:
  #是否开启限流
  enable: true
  #最大请求数；单位：个
  max-request: 10
  #窗口大小；单位：秒
  window-size: 1
#大文件存储路径
storage:
  big-file:
    location: D:/bigFile