server:
  port: 8081
  servlet:
    context-path: /
  tomcat:
    connection-timeout: 10000
spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
#  config:
#    #指定配置文件
#    location: classpath:/application.yml
#    #指定额外配置文件（会覆盖掉相同的配置，额外配置优先级最高）
#    import: classpath:application-dev.yml
  mvc:
    async:
      request-timeout: 150000
  application:
    name: cyx
  servlet:
    multipart:
      enabled: true
  mail:
    host: smtp.qq.com
    port: 587
    #发送方邮箱
    username:
    #授权码
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8
  rabbitmq:
    host: 192.168.226.130
    port: 5672
    username: root
    password: 123456
    virtual-host: /
  jmx:
    # 启动JMX监控，jconsole
    enabled: true
#mybatis配置
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 0
      logic-not-delete-value: 1
      logic-delete-field: delFlag
  type-aliases-package: com.soft.base.entity, com.soft.base.model.request, com.soft.base.model.vo, com.soft.base.model.dto
# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    #标签排序
    tags-sorter: alpha
    #接口排序
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'system'
      paths-to-match: '/**'
      packages-to-scan: com.soft.base.controller
# knife4j的增强配置
knife4j:
  production: false
  enable: true
  setting:
    language: zh_cn
    swagger-model-name: 实体列表
#jwt；已弃用
jwt:
  #密钥
  secret-key: abcdefghijklmnopq123456789
  #单位秒；1小时过期
  expire: 3600000
#minio对象存储
minio:
  url: http://192.168.226.130:9002
  accessKey: admin
  secretKey: 123456789
  bucket: cyx
#不鉴权url
permit:
  urls:
    - /auth/**
    - /doc.html
    - /message/sendRegistCaptCha
    - /message/sendLoginCaptcha
    - /ws/**
    - /secretKey/getPublicKey
    - /error
    - /favicon.ico

#登录验证码
manage-system:
  captcha:
    #主题
    topic: 管理系统登录验证码
    #验证码过期时间（秒）
    expire-time: 300
  graphics:
    #图形验证码过期时间（秒）
    expire-time: 20
  token:
    #token过期时间（秒）
    expire-time: 36000
#webclient配置
web-client:
  #响应超时；单位：秒
  response-timeout: 5
  #连接超时；单位：毫秒
  connect-timeout: 5000