server:
  port: 8081
  servlet:
    context-path: /
  tomcat:
    # 连接超时（毫秒）
    connection-timeout: 60000
    # 保持连接时长（毫秒）
    keep-alive-timeout: 30000
    remoteip:
      # 明确指定解析真实 IP 的头
      remote-ip-header: X-Forwarded-For
  forward-headers-strategy: native

spring:
  threads:
    virtual:
      enabled: true
  ai:
    deepseek:
      api-key: ${DEEPSEEK_API_KEY}
      base-url: ${DEEPSEEK_BASE_URL}
      chat:
        model: ${DEEPSEEK_MODEL}
    model:
      chat: deepseek
    max-context-num: 7
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
#  config:
#    #指定配置文件
#    location: classpath:/application.yml
#    #指定额外配置文件（会覆盖掉相同的配置，额外配置优先级最高）
#    import: classpath:application-dev.yml
  application:
    name: radish
  servlet:
    multipart:
      enabled: true
  mail:
    host: smtp.qq.com
    port: 587
    # 发送方邮箱
    username: ${EMAIL_USERNAME}
    # 授权码
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8

# mybatis配置
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  global-config:
    db-config:
      id-type: assign_id
      logic-delete-value: 1
      logic-not-delete-value: 0
      logic-delete-field: delFlag
  type-aliases-package: com.soft.sys.entity, com.soft.sys.model.request, com.soft.sys.model.vo, com.soft.sys.model.dto

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    # 标签排序
    tags-sorter: alpha
    # 接口排序
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'system'
      paths-to-match: '/**'
      packages-to-scan: com.soft.sys.controller
    - group: 'module'
      paths-to-match: '/**'
      packages-to-scan: com.soft.module.controller

# knife4j的增强配置
knife4j:
  production: false
  enable: false
  setting:
    language: zh_cn
    swagger-model-name: 实体列表

# webclient配置
web-client:
  response-timeout: 30
  connect-timeout: 10000
  pool:
    max-connection: 100
    pending-acquire-timeout: 30
    max-idle-time: 30
    max-life-time: 300
    evict-in-background: 120

# minio对象存储
minio:
  url: ${MINIO_URL}
  accessKey: ${MINIO_ACCESS_KEY}
  secretKey: ${MINIO_SECRET_KEY}
  default-bucket: ${MINIO_DEFAULT_BUCKET}
  expire: 3600

geo:
  gaode:
    api-key: ${GAO_DE_API_KEY}