CREATE TABLE `sys_actuator` (
                                `id` bigint NOT NULL,
                                `create_by` bigint DEFAULT NULL,
                                `create_time` datetime DEFAULT NULL,
                                `update_by` bigint DEFAULT NULL,
                                `update_time` datetime DEFAULT NULL,
                                `del_flag` char(1) COLLATE utf8mb4_general_ci DEFAULT NULL,
                                `cpu_usage` double(5,2) DEFAULT NULL COMMENT 'cpu使用率',
                                `cpu_count` tinyint unsigned DEFAULT NULL COMMENT 'cpu核心数',
                                `memery_used` bigint DEFAULT NULL COMMENT '内存使用量',
                                `memery_max` bigint DEFAULT NULL COMMENT '最大内存容量',
                                `uptime` bigint DEFAULT NULL COMMENT '系统运行时长',
                                `disk_free` bigint DEFAULT NULL COMMENT '磁盘空闲空间',
                                `disk_total` bigint DEFAULT NULL COMMENT '磁盘总量',
                                `health_db` varchar(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '数据库状态；up：正常；down：异常',
                                `health_disk_space` varchar(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '磁盘状态；up：正常；down：异常',
                                `health_mail` varchar(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '邮箱状态；up：正常；down：异常',
                                `health_ping` varchar(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '系统响应状态；up：正常；down：异常',
                                `health_rabbit` varchar(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT 'rabbitmq状态；up：正常；down：异常',
                                `health_redis` varchar(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT 'redis状态；up：正常；down：异常',
                                `health_ssl` varchar(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT 'ssl证书状态；up：正常；down：异常',
                                `health` varchar(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '健康状态；up：正常；down：异常',
                                PRIMARY KEY (`id`),
                                KEY `sys_actuator_create_time_IDX` (`create_time`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='系统监控表';